---
label: Project
hide_body: true
display_field: customer
fields:
- name: index
  type: number
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
    required: true
  label: Index
- name: customer
  type: text
  config:
    required: true
  label: Customer
- name: services
  type: tag_list
  default:
  - Huisstijl
  - Website
  - Fotografie
  label: Services
- name: title
  type: text
  config:
    required: true
  label: Title
- name: introduction
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Introduction
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
- name: content
  type: blocks
  label: Content
  template_types: []
  config:
    min: 
    max: 
pages:
- content/projects/design-for-designers.md
- content/projects/projectuitleg-in-duidelijke-titel.md
